# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(443, 297)
        Dialog.setStyleSheet("QWidget {\n"
"    font-family:Tahoma;\n"
"    font-weight : bold\n"
"}\n"
"\n"
"QWidget#container{\n"
"    background-color : rgb(255,255,255);\n"
"    border-bottom-right-radius:5px;\n"
"    border-bottom-left-radius:5px;\n"
"}\n"
"QWidget#title {\n"
"    background-color :rgb(69, 139, 198);\n"
"    border-top-right-radius:5px;\n"
"    border-top-left-radius:5px;\n"
"}\n"
"QWidget#title QPushButton {\n"
"    border:none;\n"
"    font-size:14px;    \n"
"    color:rgb(255,255,255)\n"
"}\n"
"QPushButton#btn_close:hover {\n"
"    color: rgb(255, 90, 14);\n"
"}\n"
"\n"
"QPushButton#minimum:hover {\n"
"    color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"QLabel#app_name {\n"
"    font-size:22px;\n"
"    color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border:none;\n"
"    border-bottom:1px solid rgb(97, 97, 97);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border:none;\n"
"    border-bottom:2px solid rgb(69, 139, 198);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border:none;\n"
"    border-bottom:2px solid rgb(69, 139, 198);\n"
"}\n"
"\n"
"QPushButton#btn_login {\n"
"    background-color :rgb(69, 139, 198);\n"
"    border-radius:8px;\n"
"    color : rgb(250,255,255);\n"
"    font-size:15px\n"
"}\n"
"\n"
"QPushButton#btn_login:hover {\n"
"    background-color :rgb(58, 117, 166);\n"
"\n"
"}\n"
"\n"
"QPushButton#btn_login:pressed {\n"
"    padding-left:3px;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QWidget(Dialog)
        self.title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.title.setStyleSheet("")
        self.title.setObjectName("title")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.khoangtrang = QtWidgets.QLabel(self.title)
        self.khoangtrang.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.khoangtrang.setStyleSheet("color: rgb(255, 255, 255);")
        self.khoangtrang.setText("")
        self.khoangtrang.setObjectName("khoangtrang")
        self.horizontalLayout.addWidget(self.khoangtrang)
        self.custom_btn = QtWidgets.QWidget(self.title)
        self.custom_btn.setMaximumSize(QtCore.QSize(66, 16777215))
        self.custom_btn.setObjectName("custom_btn")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.custom_btn)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimum = QtWidgets.QPushButton(self.custom_btn)
        self.minimum.setMinimumSize(QtCore.QSize(28, 28))
        self.minimum.setObjectName("minimum")
        self.horizontalLayout_2.addWidget(self.minimum)
        self.btn_close = QtWidgets.QPushButton(self.custom_btn)
        self.btn_close.setMinimumSize(QtCore.QSize(28, 28))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.custom_btn)
        self.verticalLayout.addWidget(self.title)
        self.container = QtWidgets.QWidget(Dialog)
        self.container.setStyleSheet("")
        self.container.setObjectName("container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout_2.setContentsMargins(40, 25, 40, 25)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.app_name = QtWidgets.QLabel(self.container)
        self.app_name.setMinimumSize(QtCore.QSize(0, 40))
        self.app_name.setMaximumSize(QtCore.QSize(16777215, 40))
        self.app_name.setObjectName("app_name")
        self.verticalLayout_2.addWidget(self.app_name, 0, QtCore.Qt.AlignHCenter)
        self.username = QtWidgets.QLineEdit(self.container)
        self.username.setMinimumSize(QtCore.QSize(0, 30))
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.verticalLayout_2.addWidget(self.username)
        self.password = QtWidgets.QLineEdit(self.container)
        self.password.setMinimumSize(QtCore.QSize(0, 30))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.verticalLayout_2.addWidget(self.password)
        self.label = QtWidgets.QLabel(self.container)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.btn_login = QtWidgets.QPushButton(self.container)
        self.btn_login.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_2.addWidget(self.btn_login)
        self.verticalLayout.addWidget(self.container)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Đăng nhập"))
        self.minimum.setText(_translate("Dialog", "-"))
        self.btn_close.setText(_translate("Dialog", "X"))
        self.app_name.setText(_translate("Dialog", "ĐĂNG NHẬP KIỂM KHÁCH"))
        self.btn_login.setText(_translate("Dialog", "ĐĂNG NHẬP"))
        self.btn_login.setShortcut(_translate("Dialog", "Return"))
