# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 331)
        MainWindow.setMinimumSize(QtCore.QSize(779, 0))
        MainWindow.setMaximumSize(QtCore.QSize(779, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stylesheet = QtWidgets.QWidget(self.centralwidget)
        self.stylesheet.setStyleSheet("QLabel#app_logo {\n"
"    border-image: url(:/ico/app/templates/icon/logo.ico);\n"
"}\n"
"\n"
"QWidget#title {\n"
"    background-color :rgb(69, 139, 198)\n"
"}\n"
"QWidget {\n"
"    font-family:Tahoma;\n"
"    font-weight : bold;\n"
"    font-size:10px;\n"
"}\n"
"QLabel#label {\n"
"    font-size:13px;\n"
"}\n"
"QTextBrowser#noidungcopy_tb,\n"
"QTextBrowser#noidungcopy_t2_tb {\n"
"    font-size:11px;\n"
"}\n"
"QWidget#title {\n"
"    background-color :rgb(69, 139, 198);\n"
"    border-top-right-radius:5px;\n"
"    border-top-left-radius:5px;\n"
"}\n"
"QWidget#title QPushButton {\n"
"    border:no;\n"
"    font-size:12px;    \n"
"    color:rgb(255,255,255)\n"
"}\n"
"QPushButton#btn_close:hover {\n"
"    color: rgb(255, 90, 14);\n"
"}\n"
"\n"
"QPushButton#minimum:hover {\n"
"    color: rgb(212, 212, 212);\n"
"}\n"
"/*__________________________________*/\n"
"\n"
"QWidget#container{\n"
"    background-color : rgb(255,255,255);\n"
"    border-bottom-right-radius:5px;\n"
"    border-bottom-left-radius:5px;\n"
"}\n"
"\n"
"QWidget#widget_top QPlainTextEdit, \n"
"QWidget#groupBox_4 QPlainTextEdit {\n"
"    font-size:12px;\n"
"}\n"
"QGroupBox#mkt_grb QLineEdit {\n"
"    font-size:11px;\n"
"}\n"
"QGroupBox#mkt_grb QComboBox {\n"
"    font-size:11px;\n"
"}\n"
"QGroupBox#tbp_grb QLabel {\n"
"    font-size:11px;    \n"
"    color: rgb(69, 139, 198);\n"
"}\n"
"QGroupBox#kteam_grb QLineEdit {\n"
"    font-size:12px;\n"
"}\n"
"QWidget#widget_right QComboBox {\n"
"    font-size:12px\n"
"}\n"
"QLineEdit#tentaikhoan_le {\n"
"font-size:11px\n"
"}\n"
"\n"
"\n"
"QWidget#container QPushButton {\n"
"    border-radius:5px;\n"
"    background-color : rgb(69, 139, 198);\n"
"    color:rgb(255,255,255);\n"
"    border:none;\n"
"}\n"
"QWidget#container QPushButton:hover {\n"
"    background-color: rgb(50, 102, 145);\n"
"}\n"
"\n"
"QPushButton#kiemtra_btn {\n"
"    font-size:16px;\n"
"\n"
"}\n"
"QWidget#container QPushButton::pressed {\n"
"    background-color :rgb(83, 168, 238);\n"
"    padding-left:1px\n"
"}\n"
"\n"
"    /* QPROGRESSBER */\n"
"QProgressBar {\n"
"    min-height: 14px;\n"
"    max-height: 14px;\n"
"    min-width: 150px;\n"
"    border-radius: 7px;\n"
"    background: rgb(240, 240, 240);\n"
"    color :rgb(0,0,0);\n"
"    font-weight : bold;\n"
"    border:1px solid rgb(255,255,255)\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 7px;\n"
"    background-color:rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton#napdulieu_btn:hover {\n"
"    color: rgb(112, 193, 255);\n"
"}\n"
"\n"
"QPushButton#napdulieu_btn:pressed {\n"
"    padding-left:3px\n"
"}\n"
"QLineEdit#tentaikhoan {\n"
"    font-size:11px\n"
"\n"
"}\n"
"")
        self.stylesheet.setObjectName("stylesheet")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stylesheet)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QWidget(self.stylesheet)
        self.title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.title.setStyleSheet("")
        self.title.setObjectName("title")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.title)
        self.horizontalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.app_logo = QtWidgets.QLabel(self.title)
        self.app_logo.setMinimumSize(QtCore.QSize(22, 22))
        self.app_logo.setMaximumSize(QtCore.QSize(22, 22))
        self.app_logo.setStyleSheet("")
        self.app_logo.setText("")
        self.app_logo.setObjectName("app_logo")
        self.horizontalLayout_2.addWidget(self.app_logo)
        self.app_name = QtWidgets.QLabel(self.title)
        self.app_name.setMaximumSize(QtCore.QSize(110, 16777215))
        self.app_name.setObjectName("app_name")
        self.horizontalLayout_2.addWidget(self.app_name)
        self.napdulieu_btn = QtWidgets.QPushButton(self.title)
        self.napdulieu_btn.setMaximumSize(QtCore.QSize(110, 16777215))
        self.napdulieu_btn.setObjectName("napdulieu_btn")
        self.horizontalLayout_2.addWidget(self.napdulieu_btn)
        self.progressBar = QtWidgets.QProgressBar(self.title)
        self.progressBar.setMinimumSize(QtCore.QSize(152, 16))
        self.progressBar.setMaximumSize(QtCore.QSize(150, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.label = QtWidgets.QLabel(self.title)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.title)
        self.spinBox.setMinimumSize(QtCore.QSize(50, 24))
        self.spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMinimum(5)
        self.spinBox.setMaximum(120)
        self.spinBox.setSingleStep(10)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.custom_btn = QtWidgets.QWidget(self.title)
        self.custom_btn.setMaximumSize(QtCore.QSize(66, 16777215))
        self.custom_btn.setObjectName("custom_btn")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.custom_btn)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.minimum = QtWidgets.QPushButton(self.custom_btn)
        self.minimum.setMinimumSize(QtCore.QSize(28, 28))
        self.minimum.setObjectName("minimum")
        self.horizontalLayout_11.addWidget(self.minimum)
        self.btn_close = QtWidgets.QPushButton(self.custom_btn)
        self.btn_close.setMinimumSize(QtCore.QSize(28, 28))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_11.addWidget(self.btn_close)
        self.horizontalLayout_2.addWidget(self.custom_btn)
        self.verticalLayout_2.addWidget(self.title)
        self.container = QtWidgets.QWidget(self.stylesheet)
        self.container.setObjectName("container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.container)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top = QtWidgets.QWidget(self.page)
        self.widget_top.setMinimumSize(QtCore.QSize(0, 86))
        self.widget_top.setMaximumSize(QtCore.QSize(16777215, 86))
        self.widget_top.setObjectName("widget_top")
        self.plainTextEdit_tha = QtWidgets.QPlainTextEdit(self.widget_top)
        self.plainTextEdit_tha.setGeometry(QtCore.QRect(120, 44, 636, 40))
        self.plainTextEdit_tha.setObjectName("plainTextEdit_tha")
        self.label_ku = QtWidgets.QLabel(self.widget_top)
        self.label_ku.setGeometry(QtCore.QRect(100, 15, 21, 20))
        self.label_ku.setObjectName("label_ku")
        self.label_tha = QtWidgets.QLabel(self.widget_top)
        self.label_tha.setGeometry(QtCore.QRect(95, 50, 26, 20))
        self.label_tha.setObjectName("label_tha")
        self.kiemtra_btn = QtWidgets.QPushButton(self.widget_top)
        self.kiemtra_btn.setGeometry(QtCore.QRect(5, 45, 86, 36))
        self.kiemtra_btn.setStyleSheet("font-size:13px;")
        self.kiemtra_btn.setObjectName("kiemtra_btn")
        self.plainTextEdit_ku = QtWidgets.QPlainTextEdit(self.widget_top)
        self.plainTextEdit_ku.setGeometry(QtCore.QRect(120, 3, 636, 40))
        self.plainTextEdit_ku.setObjectName("plainTextEdit_ku")
        self.tentaikhoan_le = QtWidgets.QLineEdit(self.widget_top)
        self.tentaikhoan_le.setGeometry(QtCore.QRect(5, 5, 86, 41))
        self.tentaikhoan_le.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tentaikhoan_le.setText("")
        self.tentaikhoan_le.setObjectName("tentaikhoan_le")
        self.verticalLayout.addWidget(self.widget_top)
        self.widget_tong_duoi = QtWidgets.QWidget(self.page)
        self.widget_tong_duoi.setObjectName("widget_tong_duoi")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_tong_duoi)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_left = QtWidgets.QWidget(self.widget_tong_duoi)
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_mkt = QtWidgets.QWidget(self.widget_left)
        self.widget_mkt.setObjectName("widget_mkt")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_mkt)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mkt_grb = QtWidgets.QGroupBox(self.widget_mkt)
        self.mkt_grb.setObjectName("mkt_grb")
        self.napsau90n_btn = QtWidgets.QPushButton(self.mkt_grb)
        self.napsau90n_btn.setGeometry(QtCore.QRect(235, 76, 111, 23))
        self.napsau90n_btn.setObjectName("napsau90n_btn")
        self.chuyenlinhchua_btn = QtWidgets.QPushButton(self.mkt_grb)
        self.chuyenlinhchua_btn.setGeometry(QtCore.QRect(235, 53, 111, 23))
        self.chuyenlinhchua_btn.setObjectName("chuyenlinhchua_btn")
        self.daily_mkt_cbb = QtWidgets.QComboBox(self.mkt_grb)
        self.daily_mkt_cbb.setGeometry(QtCore.QRect(68, 74, 65, 22))
        self.daily_mkt_cbb.setToolTip("")
        self.daily_mkt_cbb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.daily_mkt_cbb.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.daily_mkt_cbb.setObjectName("daily_mkt_cbb")
        self.daily_mkt_cbb.addItem("")
        self.daily_mkt_cbb.addItem("")
        self.daily_mkt_cbb.addItem("")
        self.daily_mkt_cbb.addItem("")
        self.daily_mkt_cbb.addItem("")
        self.daily_mkt_cbb.addItem("")
        self.daily_mkt_cbb.addItem("")
        self.daily_mkt_cbb.addItem("")
        self.daily_mkt_cbb.addItem("")
        self.napchua_btn = QtWidgets.QPushButton(self.mkt_grb)
        self.napchua_btn.setGeometry(QtCore.QRect(135, 30, 101, 23))
        self.napchua_btn.setObjectName("napchua_btn")
        self.trangthai_btn = QtWidgets.QPushButton(self.mkt_grb)
        self.trangthai_btn.setGeometry(QtCore.QRect(235, 30, 111, 23))
        self.trangthai_btn.setObjectName("trangthai_btn")
        self.sodienthoai_le = QtWidgets.QLineEdit(self.mkt_grb)
        self.sodienthoai_le.setGeometry(QtCore.QRect(2, 33, 131, 20))
        self.sodienthoai_le.setText("")
        self.sodienthoai_le.setObjectName("sodienthoai_le")
        self.tainapchua_btn = QtWidgets.QPushButton(self.mkt_grb)
        self.tainapchua_btn.setGeometry(QtCore.QRect(135, 53, 101, 23))
        self.tainapchua_btn.setObjectName("tainapchua_btn")
        self.cokhong_btn = QtWidgets.QPushButton(self.mkt_grb)
        self.cokhong_btn.setGeometry(QtCore.QRect(235, 7, 111, 23))
        self.cokhong_btn.setObjectName("cokhong_btn")
        self.xungho_mkt_cbb = QtWidgets.QComboBox(self.mkt_grb)
        self.xungho_mkt_cbb.setGeometry(QtCore.QRect(3, 74, 64, 22))
        self.xungho_mkt_cbb.setObjectName("xungho_mkt_cbb")
        self.xungho_mkt_cbb.addItem("")
        self.xungho_mkt_cbb.addItem("")
        self.mail_le = QtWidgets.QLineEdit(self.mkt_grb)
        self.mail_le.setGeometry(QtCore.QRect(2, 53, 131, 20))
        self.mail_le.setText("")
        self.mail_le.setObjectName("mail_le")
        self.conchoikhong_btn = QtWidgets.QPushButton(self.mkt_grb)
        self.conchoikhong_btn.setGeometry(QtCore.QRect(135, 76, 101, 23))
        self.conchoikhong_btn.setObjectName("conchoikhong_btn")
        self.bietdanh_le = QtWidgets.QLineEdit(self.mkt_grb)
        self.bietdanh_le.setGeometry(QtCore.QRect(2, 13, 131, 20))
        self.bietdanh_le.setText("")
        self.bietdanh_le.setObjectName("bietdanh_le")
        self.dangkychua_btn = QtWidgets.QPushButton(self.mkt_grb)
        self.dangkychua_btn.setGeometry(QtCore.QRect(135, 7, 101, 23))
        self.dangkychua_btn.setStyleSheet("")
        self.dangkychua_btn.setObjectName("dangkychua_btn")
        self.verticalLayout_4.addWidget(self.mkt_grb)
        self.verticalLayout_3.addWidget(self.widget_mkt)
        self.widget_tbp = QtWidgets.QWidget(self.widget_left)
        self.widget_tbp.setObjectName("widget_tbp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_tbp)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tbp_grb = QtWidgets.QGroupBox(self.widget_tbp)
        self.tbp_grb.setObjectName("tbp_grb")
        self.nhandiemkho_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.nhandiemkho_btn.setGeometry(QtCore.QRect(265, 71, 86, 23))
        self.nhandiemkho_btn.setObjectName("nhandiemkho_btn")
        self.clink90n_bdanh_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.clink90n_bdanh_btn.setGeometry(QtCore.QRect(80, 48, 76, 23))
        self.clink90n_bdanh_btn.setObjectName("clink90n_bdanh_btn")
        self.doiten_khacbp_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.doiten_khacbp_btn.setGeometry(QtCore.QRect(265, 25, 86, 23))
        self.doiten_khacbp_btn.setObjectName("doiten_khacbp_btn")
        self.lienhedk_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.lienhedk_btn.setGeometry(QtCore.QRect(160, 48, 106, 23))
        self.lienhedk_btn.setObjectName("lienhedk_btn")
        self.dkncngoai_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.dkncngoai_btn.setGeometry(QtCore.QRect(160, 71, 106, 23))
        self.dkncngoai_btn.setObjectName("dkncngoai_btn")
        self.clink12h_bdanh_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.clink12h_bdanh_btn.setGeometry(QtCore.QRect(80, 25, 76, 23))
        self.clink12h_bdanh_btn.setObjectName("clink12h_bdanh_btn")
        self.truongbp_4 = QtWidgets.QLabel(self.tbp_grb)
        self.truongbp_4.setGeometry(QtCore.QRect(195, 5, 116, 20))
        self.truongbp_4.setAlignment(QtCore.Qt.AlignCenter)
        self.truongbp_4.setObjectName("truongbp_4")
        self.clink90n_sdt_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.clink90n_sdt_btn.setGeometry(QtCore.QRect(0, 48, 81, 23))
        self.clink90n_sdt_btn.setObjectName("clink90n_sdt_btn")
        self.monapmail_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.monapmail_btn.setGeometry(QtCore.QRect(265, 48, 86, 23))
        self.monapmail_btn.setObjectName("monapmail_btn")
        self.clink12h_sdt_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.clink12h_sdt_btn.setGeometry(QtCore.QRect(0, 25, 81, 23))
        self.clink12h_sdt_btn.setObjectName("clink12h_sdt_btn")
        self.thugon_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.thugon_btn.setGeometry(QtCore.QRect(-10, 75, 71, 21))
        self.thugon_btn.setStyleSheet("border:none;\n"
"color : rgb(0, 170, 255);\n"
"background:transparent")
        self.thugon_btn.setObjectName("thugon_btn")
        self.doiten_cungbp_btn = QtWidgets.QPushButton(self.tbp_grb)
        self.doiten_cungbp_btn.setGeometry(QtCore.QRect(160, 25, 106, 23))
        self.doiten_cungbp_btn.setObjectName("doiten_cungbp_btn")
        self.truongbp_2 = QtWidgets.QLabel(self.tbp_grb)
        self.truongbp_2.setGeometry(QtCore.QRect(5, 8, 76, 20))
        self.truongbp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.truongbp_2.setObjectName("truongbp_2")
        self.truongbp_3 = QtWidgets.QLabel(self.tbp_grb)
        self.truongbp_3.setGeometry(QtCore.QRect(80, 8, 76, 20))
        self.truongbp_3.setAlignment(QtCore.Qt.AlignCenter)
        self.truongbp_3.setObjectName("truongbp_3")
        self.verticalLayout_5.addWidget(self.tbp_grb)
        self.verticalLayout_3.addWidget(self.widget_tbp)
        self.horizontalLayout_4.addWidget(self.widget_left)
        self.widget_right = QtWidgets.QWidget(self.widget_tong_duoi)
        self.widget_right.setMinimumSize(QtCore.QSize(410, 0))
        self.widget_right.setObjectName("widget_right")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_right)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_kteam = QtWidgets.QWidget(self.widget_right)
        self.widget_kteam.setObjectName("widget_kteam")
        self.kteam_grb = QtWidgets.QGroupBox(self.widget_kteam)
        self.kteam_grb.setGeometry(QtCore.QRect(0, 1, 405, 84))
        self.kteam_grb.setStyleSheet("font-size:9px")
        self.kteam_grb.setObjectName("kteam_grb")
        self.ruttien_btn = QtWidgets.QPushButton(self.kteam_grb)
        self.ruttien_btn.setGeometry(QtCore.QRect(335, 58, 66, 23))
        self.ruttien_btn.setObjectName("ruttien_btn")
        self.daily_k_cbb = QtWidgets.QComboBox(self.kteam_grb)
        self.daily_k_cbb.setGeometry(QtCore.QRect(120, 33, 62, 22))
        self.daily_k_cbb.setToolTip("")
        self.daily_k_cbb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.daily_k_cbb.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.daily_k_cbb.setObjectName("daily_k_cbb")
        self.daily_k_cbb.addItem("")
        self.daily_k_cbb.addItem("")
        self.daily_k_cbb.addItem("")
        self.daily_k_cbb.addItem("")
        self.daily_k_cbb.addItem("")
        self.daily_k_cbb.addItem("")
        self.daily_k_cbb.addItem("")
        self.daily_k_cbb.addItem("")
        self.taitha_btn = QtWidgets.QPushButton(self.kteam_grb)
        self.taitha_btn.setGeometry(QtCore.QRect(190, 35, 71, 23))
        self.taitha_btn.setObjectName("taitha_btn")
        self.nhandiem_btn = QtWidgets.QPushButton(self.kteam_grb)
        self.nhandiem_btn.setGeometry(QtCore.QRect(260, 58, 76, 23))
        self.nhandiem_btn.setObjectName("nhandiem_btn")
        self.monapku_btn = QtWidgets.QPushButton(self.kteam_grb)
        self.monapku_btn.setGeometry(QtCore.QRect(260, 12, 76, 23))
        self.monapku_btn.setMinimumSize(QtCore.QSize(76, 0))
        self.monapku_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.monapku_btn.setObjectName("monapku_btn")
        self.naptien_btn = QtWidgets.QPushButton(self.kteam_grb)
        self.naptien_btn.setGeometry(QtCore.QRect(335, 12, 66, 23))
        self.naptien_btn.setObjectName("naptien_btn")
        self.tlzlfb_cbb = QtWidgets.QComboBox(self.kteam_grb)
        self.tlzlfb_cbb.setGeometry(QtCore.QRect(2, 12, 70, 22))
        self.tlzlfb_cbb.setToolTip("")
        self.tlzlfb_cbb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tlzlfb_cbb.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.tlzlfb_cbb.setObjectName("tlzlfb_cbb")
        self.tlzlfb_cbb.addItem("")
        self.tlzlfb_cbb.addItem("")
        self.tlzlfb_cbb.addItem("")
        self.tenkhach_le = QtWidgets.QLineEdit(self.kteam_grb)
        self.tenkhach_le.setGeometry(QtCore.QRect(72, 13, 110, 20))
        self.tenkhach_le.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tenkhach_le.setText("")
        self.tenkhach_le.setObjectName("tenkhach_le")
        self.laylaitk_btn = QtWidgets.QPushButton(self.kteam_grb)
        self.laylaitk_btn.setGeometry(QtCore.QRect(190, 58, 71, 23))
        self.laylaitk_btn.setObjectName("laylaitk_btn")
        self.hddangky_btn = QtWidgets.QPushButton(self.kteam_grb)
        self.hddangky_btn.setGeometry(QtCore.QRect(72, 54, 111, 23))
        self.hddangky_btn.setObjectName("hddangky_btn")
        self.tainap_btn = QtWidgets.QPushButton(self.kteam_grb)
        self.tainap_btn.setGeometry(QtCore.QRect(335, 35, 66, 23))
        self.tainap_btn.setObjectName("tainap_btn")
        self.monaptha_btn = QtWidgets.QPushButton(self.kteam_grb)
        self.monaptha_btn.setGeometry(QtCore.QRect(260, 35, 76, 23))
        self.monaptha_btn.setObjectName("monaptha_btn")
        self.xungho_k_cbb = QtWidgets.QComboBox(self.kteam_grb)
        self.xungho_k_cbb.setGeometry(QtCore.QRect(72, 33, 50, 22))
        self.xungho_k_cbb.setObjectName("xungho_k_cbb")
        self.xungho_k_cbb.addItem("")
        self.xungho_k_cbb.addItem("")
        self.taiku_btn = QtWidgets.QPushButton(self.kteam_grb)
        self.taiku_btn.setGeometry(QtCore.QRect(190, 12, 71, 23))
        self.taiku_btn.setObjectName("taiku_btn")
        self.noidungcopy_tb = QtWidgets.QTextBrowser(self.widget_kteam)
        self.noidungcopy_tb.setGeometry(QtCore.QRect(0, 85, 406, 111))
        self.noidungcopy_tb.setObjectName("noidungcopy_tb")
        self.verticalLayout_6.addWidget(self.widget_kteam)
        self.horizontalLayout_4.addWidget(self.widget_right)
        self.verticalLayout.addWidget(self.widget_tong_duoi)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 3, 755, 106))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(120, 10, 21, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(120, 45, 26, 20))
        self.label_14.setObjectName("label_14")
        self.tentaikhoan_t2_le = QtWidgets.QLineEdit(self.groupBox_4)
        self.tentaikhoan_t2_le.setGeometry(QtCore.QRect(2, 0, 113, 29))
        self.tentaikhoan_t2_le.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tentaikhoan_t2_le.setText("")
        self.tentaikhoan_t2_le.setObjectName("tentaikhoan_t2_le")
        self.cokhong_t2_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.cokhong_t2_btn.setGeometry(QtCore.QRect(0, 80, 66, 23))
        self.cokhong_t2_btn.setObjectName("cokhong_t2_btn")
        self.conchoikhong_t2_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.conchoikhong_t2_btn.setGeometry(QtCore.QRect(65, 80, 111, 23))
        self.conchoikhong_t2_btn.setObjectName("conchoikhong_t2_btn")
        self.trangthai_t2_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.trangthai_t2_btn.setGeometry(QtCore.QRect(175, 80, 91, 23))
        self.trangthai_t2_btn.setObjectName("trangthai_t2_btn")
        self.noidungcopy_t2_tb = QtWidgets.QTextBrowser(self.groupBox_4)
        self.noidungcopy_t2_tb.setGeometry(QtCore.QRect(266, 80, 441, 23))
        self.noidungcopy_t2_tb.setObjectName("noidungcopy_t2_tb")
        self.daily_t2_btn = QtWidgets.QComboBox(self.groupBox_4)
        self.daily_t2_btn.setGeometry(QtCore.QRect(60, 55, 55, 22))
        self.daily_t2_btn.setToolTip("")
        self.daily_t2_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.daily_t2_btn.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.daily_t2_btn.setObjectName("daily_t2_btn")
        self.daily_t2_btn.addItem("")
        self.daily_t2_btn.addItem("")
        self.daily_t2_btn.addItem("")
        self.daily_t2_btn.addItem("")
        self.daily_t2_btn.addItem("")
        self.daily_t2_btn.addItem("")
        self.daily_t2_btn.addItem("")
        self.daily_t2_btn.addItem("")
        self.xungho_t2_btn = QtWidgets.QComboBox(self.groupBox_4)
        self.xungho_t2_btn.setGeometry(QtCore.QRect(0, 55, 61, 22))
        self.xungho_t2_btn.setObjectName("xungho_t2_btn")
        self.xungho_t2_btn.addItem("")
        self.xungho_t2_btn.addItem("")
        self.kiemtra_t2_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.kiemtra_t2_btn.setGeometry(QtCore.QRect(2, 30, 113, 21))
        self.kiemtra_t2_btn.setStyleSheet("")
        self.kiemtra_t2_btn.setObjectName("kiemtra_t2_btn")
        self.morong_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.morong_btn.setGeometry(QtCore.QRect(710, 80, 46, 21))
        self.morong_btn.setStyleSheet("border:none;\n"
"color : rgb(0, 170, 255);\n"
"background:transparent;")
        self.morong_btn.setObjectName("morong_btn")
        self.plainTextEdit_t2_tha = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit_t2_tha.setGeometry(QtCore.QRect(150, 40, 601, 40))
        self.plainTextEdit_t2_tha.setMinimumSize(QtCore.QSize(0, 40))
        self.plainTextEdit_t2_tha.setObjectName("plainTextEdit_t2_tha")
        self.plainTextEdit_t2_ku = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit_t2_ku.setGeometry(QtCore.QRect(150, 0, 601, 40))
        self.plainTextEdit_t2_ku.setMinimumSize(QtCore.QSize(0, 40))
        self.plainTextEdit_t2_ku.setStyleSheet("")
        self.plainTextEdit_t2_ku.setObjectName("plainTextEdit_t2_ku")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.container)
        self.horizontalLayout.addWidget(self.stylesheet)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.app_name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">KIỂM KHÁCH HCK</span></p></body></html>"))
        self.napdulieu_btn.setText(_translate("MainWindow", "NẠP DỮ LIỆU"))
        self.label.setText(_translate("MainWindow", "VUI LÒNG NẠP DỮ LIỆU"))
        self.minimum.setText(_translate("MainWindow", "-"))
        self.btn_close.setText(_translate("MainWindow", "X"))
        self.label_ku.setText(_translate("MainWindow", "KU"))
        self.label_tha.setText(_translate("MainWindow", "THA"))
        self.kiemtra_btn.setText(_translate("MainWindow", "KIỂM TRA"))
        self.kiemtra_btn.setShortcut(_translate("MainWindow", "Return"))
        self.tentaikhoan_le.setPlaceholderText(_translate("MainWindow", "Tên tài khoản"))
        self.mkt_grb.setTitle(_translate("MainWindow", "MKT"))
        self.napsau90n_btn.setText(_translate("MainWindow", "NẠP SAU 90N CHƯA"))
        self.chuyenlinhchua_btn.setText(_translate("MainWindow", "CHUYỂN LINK CHƯA"))
        self.daily_mkt_cbb.setItemText(0, _translate("MainWindow", "KU"))
        self.daily_mkt_cbb.setItemText(1, _translate("MainWindow", "THA"))
        self.daily_mkt_cbb.setItemText(2, _translate("MainWindow", "KU+THA"))
        self.daily_mkt_cbb.setItemText(3, _translate("MainWindow", "DV31"))
        self.daily_mkt_cbb.setItemText(4, _translate("MainWindow", "DV32"))
        self.daily_mkt_cbb.setItemText(5, _translate("MainWindow", "DV35"))
        self.daily_mkt_cbb.setItemText(6, _translate("MainWindow", "DV36"))
        self.daily_mkt_cbb.setItemText(7, _translate("MainWindow", "DV38"))
        self.daily_mkt_cbb.setItemText(8, _translate("MainWindow", "DV39"))
        self.napchua_btn.setText(_translate("MainWindow", "NẠP CHƯA"))
        self.trangthai_btn.setText(_translate("MainWindow", "TRẠNG THÁI TK"))
        self.sodienthoai_le.setPlaceholderText(_translate("MainWindow", "Số điện thoại"))
        self.tainapchua_btn.setText(_translate("MainWindow", "TÁI NẠP CHƯA"))
        self.cokhong_btn.setText(_translate("MainWindow", "CÓ KHÔNG"))
        self.xungho_mkt_cbb.setItemText(0, _translate("MainWindow", "em"))
        self.xungho_mkt_cbb.setItemText(1, _translate("MainWindow", "mình"))
        self.mail_le.setPlaceholderText(_translate("MainWindow", "Mail"))
        self.conchoikhong_btn.setText(_translate("MainWindow", "CÒN CHƠI KHÔNG"))
        self.bietdanh_le.setPlaceholderText(_translate("MainWindow", "Biệt danh"))
        self.dangkychua_btn.setText(_translate("MainWindow", "ĐĂNG KÝ CHƯA"))
        self.tbp_grb.setTitle(_translate("MainWindow", "TRƯỞNG BỘ PHẬN"))
        self.nhandiemkho_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Khách nạp chưa nhận được điểm</span></p><p>+ Liên hệ CSKH nhập điểm 40 phút trước, chưa thấy lên điểm</p><p>+ Đã xin biên lai chi tiết của khách</p><p><br/></p></body></html>"))
        self.nhandiemkho_btn.setText(_translate("MainWindow", "NHẬN ĐIỂM"))
        self.clink90n_bdanh_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Khách trên 90 ngày không đặt cược</span></p><p>+ Thuộc KU#, không tính KU trang chủ</p><p>+ Phải đăng nhập trong vòng 3 tiếng trước khí chuyển</p><p><br/></p></body></html>"))
        self.clink90n_bdanh_btn.setText(_translate("MainWindow", "C.LINK(90N)"))
        self.doiten_khacbp_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Khách NẠP LẦN ĐẦU/TÁI NẠP khác bộ phận</span> -&gt; đổi tên</p></body></html>"))
        self.doiten_khacbp_btn.setText(_translate("MainWindow", "ĐỔI TÊN (# BP)"))
        self.lienhedk_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>+ Khách quả lượt nhận mã</p><p>+ Đã bấm liên hệ máy lần nhưng không được chuyên viên gọi điện</p><p><br/></p></body></html>"))
        self.lienhedk_btn.setText(_translate("MainWindow", "LIÊN HỆ ĐĂNG KÝ"))
        self.dkncngoai_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Khách thuộc khu vực hỗ trợ đăng ký:</span></p><p>Đài Loan, Hồng Kong, Macao, Việt Nam, Campuchia, Thái Lan, Malaisia, Nhật Bản, Hàn Quốc</p><p>+ SĐT không thuộc mã vùng VN</p><p>+ Có thẻ ATM và banking VN</p><p><br/></p></body></html>"))
        self.dkncngoai_btn.setText(_translate("MainWindow", "Đ.KÝ NƯỚC NGOÀI"))
        self.clink12h_bdanh_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Khách đăng ký sai link </span></p><p>+ Không điền mã đại lý<br/>+ Khách trang chủ đăng ký trong vòng 12h chưa Bổ sung thông tin, Nạp</p></body></html>"))
        self.clink12h_bdanh_btn.setText(_translate("MainWindow", "C.LINK (12H)"))
        self.truongbp_4.setText(_translate("MainWindow", "Nạp lần đầu/Tái nạp"))
        self.clink90n_sdt_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Khách trên 90 ngày không đặt cược</span></p><p>+ Thuộc KU#, không tính KU trang chủ</p><p>+ Phải đăng nhập trong vòng 3 tiếng trước khí chuyển</p><p><br/></p></body></html>"))
        self.clink90n_sdt_btn.setText(_translate("MainWindow", "C.LINK(90N)"))
        self.monapmail_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Khách mở nạp qua mail, thông tin cần lấy:</p><p>+ Tên tài khoản</p><p>+ Biệt danh</p><p>+ Địa chỉ mail</p><p>+ 2 ảnh CMT hoặc CCCD</p></body></html>"))
        self.monapmail_btn.setText(_translate("MainWindow", "MỞ NẠP"))
        self.clink12h_sdt_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Khách đăng ký sai link </span></p><p>+ Không điền mã đại lý<br/>+ Khách trang chủ đăng ký trong vòng 12h chưa Bổ sung thông tin, Nạp</p></body></html>"))
        self.clink12h_sdt_btn.setText(_translate("MainWindow", "C.LINK (12H)"))
        self.thugon_btn.setText(_translate("MainWindow", "Thu gọn"))
        self.doiten_cungbp_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Khách NẠP LẦN ĐẦU/TÁI NẠP cùng bộ phận</span> -&gt; đổi tên</p></body></html>"))
        self.doiten_cungbp_btn.setText(_translate("MainWindow", "ĐỔI TÊN (CÙNG BP)"))
        self.truongbp_2.setText(_translate("MainWindow", "Số điện thoại"))
        self.truongbp_3.setText(_translate("MainWindow", "Biệt danh"))
        self.kteam_grb.setTitle(_translate("MainWindow", "K TEAM"))
        self.ruttien_btn.setText(_translate("MainWindow", "RÚT TIỀN"))
        self.daily_k_cbb.setItemText(0, _translate("MainWindow", "KU"))
        self.daily_k_cbb.setItemText(1, _translate("MainWindow", "THA"))
        self.daily_k_cbb.setItemText(2, _translate("MainWindow", "DV31"))
        self.daily_k_cbb.setItemText(3, _translate("MainWindow", "DV32"))
        self.daily_k_cbb.setItemText(4, _translate("MainWindow", "DV35"))
        self.daily_k_cbb.setItemText(5, _translate("MainWindow", "DV36"))
        self.daily_k_cbb.setItemText(6, _translate("MainWindow", "DV38"))
        self.daily_k_cbb.setItemText(7, _translate("MainWindow", "DV39"))
        self.taitha_btn.setText(_translate("MainWindow", "TẢI THA"))
        self.nhandiem_btn.setText(_translate("MainWindow", "NHẬN ĐIỂM"))
        self.monapku_btn.setText(_translate("MainWindow", "MỞ NẠP KU"))
        self.naptien_btn.setText(_translate("MainWindow", "NẠP TIỀN"))
        self.tlzlfb_cbb.setItemText(0, _translate("MainWindow", "Zalo"))
        self.tlzlfb_cbb.setItemText(1, _translate("MainWindow", "Facebook"))
        self.tlzlfb_cbb.setItemText(2, _translate("MainWindow", "Telegram"))
        self.tenkhach_le.setPlaceholderText(_translate("MainWindow", "Tên FB/Zl/Tl"))
        self.laylaitk_btn.setText(_translate("MainWindow", "LẤY LẠI TK"))
        self.hddangky_btn.setText(_translate("MainWindow", "HD ĐĂNG KÝ"))
        self.tainap_btn.setText(_translate("MainWindow", "TÁI NẠP"))
        self.monaptha_btn.setText(_translate("MainWindow", "MỞ NẠP THA"))
        self.xungho_k_cbb.setItemText(0, _translate("MainWindow", "em"))
        self.xungho_k_cbb.setItemText(1, _translate("MainWindow", "mình"))
        self.taiku_btn.setText(_translate("MainWindow", "TẢI KU"))
        self.label_13.setText(_translate("MainWindow", "KU"))
        self.label_14.setText(_translate("MainWindow", "THA"))
        self.tentaikhoan_t2_le.setPlaceholderText(_translate("MainWindow", "Tên tài khoản"))
        self.cokhong_t2_btn.setText(_translate("MainWindow", "CÓ KHÔNG"))
        self.conchoikhong_t2_btn.setText(_translate("MainWindow", "CÒN CHƠI KHÔNG"))
        self.trangthai_t2_btn.setText(_translate("MainWindow", "TRẠNG THÁI TK"))
        self.daily_t2_btn.setItemText(0, _translate("MainWindow", "KU"))
        self.daily_t2_btn.setItemText(1, _translate("MainWindow", "THA"))
        self.daily_t2_btn.setItemText(2, _translate("MainWindow", "KU+THA"))
        self.daily_t2_btn.setItemText(3, _translate("MainWindow", "DV38"))
        self.daily_t2_btn.setItemText(4, _translate("MainWindow", "DV39"))
        self.daily_t2_btn.setItemText(5, _translate("MainWindow", "DV31"))
        self.daily_t2_btn.setItemText(6, _translate("MainWindow", "DV32"))
        self.daily_t2_btn.setItemText(7, _translate("MainWindow", "DV35"))
        self.xungho_t2_btn.setItemText(0, _translate("MainWindow", "em"))
        self.xungho_t2_btn.setItemText(1, _translate("MainWindow", "mình"))
        self.kiemtra_t2_btn.setText(_translate("MainWindow", "KIỂM TRA"))
        self.kiemtra_t2_btn.setShortcut(_translate("MainWindow", "Return"))
        self.morong_btn.setText(_translate("MainWindow", "Mở rộng"))
import icon_rc
